
spring.datasource.url=jdbc:postgresql://localhost:6543/testdb
spring.datasource.username=postgres
spring.datasource.password=Nicolas123.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update   
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional: más detalle en logs de consultas
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


server.port=9090   